#!/bin/sh
### BEGIN INIT INFO
# Provides:          infiniftystat
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     false
# Short-Description: infinitystat init script
# Description:       Start/stop infinitystat
### END INIT INFO

DESC="infinitystat"
NAME=infinitystat
#DAEMON=

do_start()
{
   nohup sh /usr/local/bin/infinity.sh &
   echo "Starting InfinityStat!";
}

do_stop()
{
   pkill -f /usr/local/bin/infinity.sh
   echo "Stopping InfinityStat!"
}


case "$1" in
   start)
     do_start
     ;;
   stop)
     do_stop
     ;;
esac

exit 0
